### ISSUE TITLE
Dynamic dispatch isn't respected if the aspect classes aren't in the same file

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/k3#36]
If we have 
class Parent
class ChildA   extends Parent

and 
@Aspect(className=typeof(Parent)) 
class ParentAspect
        public def String myOperation() {
        "ParentAspect("+_self.name+")"
    }
@Aspect(className=typeof(ChildA)) 
class ChildAAspect   extends ParentAspect
    public def String myOperation() {
        "ChildAAspect("+_self.name+")"
    }
...

if the ChildAAspect is located in the same file as ParentAspect, calling myOperation will correctly call the method defined in the ChildAAspect

but if the 2 aspects are in 2 separate files, this will be the parent operation that'll be called.

the generated code in ParentAspect.java doesn't contain the reference to the ChildAAspect

**Comment by tdegueul** [comment]
The `@Aspect` processor on `ParentAspect` cannot find `ChildAspect` because it uses `TypeLookup::findClass` to retrieve the inheritance hierarchy. Problem is that `findClass` can only find types within a `CompilationUnit`, which in turns represent a single Xtend file AST. In other words, an annotation processor cannot escape the file where it is used, hence I don't think we can handle this case...

cc @arnobl

**Comment by dvojtise** [comment]
If we can't do indirectly with xtend, a solution would be to:
- generate a placeholder with xtend
- with a specific builder that will happen after xtend code generation, replace this placeholder with better code with a process that searches into the whole classpath (for example using spoon, @barais  has some project example that use both spoon and xtend)
