### ISSUE TITLE
The generated Java code depends on the k3 annotations

### ISSUE THREAD

**Issue by arnobl** [diverse-project/k3#37]
The generated Java code depends on the k3 annotations (java classes are tagged with these annotations).
This dependency should be cut to export the produced Java code as purely Java code.

**Comment by dvojtise** [comment]
I theory yes,but 
1/ I'm not sure we have any control on this because this is probably an xtend behavior
2/ we need to check with Melange when it analyses K3 code to produce the extended metamodel wether it can rely only on xtend source or if its internal jvmtypes rely on the generated classes (and thus on the intermediate annotations ...)

**Comment by arnobl** [comment]
In fact Thomas needs these annotations in the Java code.
So closing the ticket.
