### ISSUE TITLE
Debug message not deleted (?)

### ISSUE THREAD

**Issue by lmouline** [diverse-project/k3#65]
I don't know if it's "normal" or not, but it seems that a debug message is still present in the code:

https://github.com/diverse-project/k3/blob/f90eeb00c1f62bb14585e3cd3fc9f1e9f3234c67/k3.eclipse/fr.inria.diverse.k3.al.annotationprocessor.plugin/src/fr/inria/diverse/k3/al/annotationprocessor/Aspect.xtend#L576

(cc @d-leroy :p)

**Comment by dvojtise** [comment]
The message is clearly inadequate. (It reports an error on the aspect class )
it need a check but it should probably be replaced by something like "Missing superlcass: declaring a method with @OverrideAspectMethod implies to have at least a parent class"

or even better, find the place (_cxt.addError(theMethod,...)_) where to add the error directly on the method with this annotation (instead of placing the error on the class containing the method)
